# Working directory
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", ".git"]

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
